name: CI/CD Build and Distribute

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-distribute:
    name: Build and Distribute to Firebase
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./riung

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Firebase Config Files
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json
          echo "${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}" > ios/Runner/GoogleService-Info.plist

      # ================== ANDROID ==================
      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: tester
          file: riung/build/app/outputs/flutter-apk/app-release.apk

      # ================== IOS ==================
      - name: Build unsigned iOS App
        run: flutter build ios --release --no-codesign

      - name: Create Unsigned IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -qq -r riung_unsigned.ipa Payload
          rm -rf Payload

      - name: Upload Unsigned IPA to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_IOS }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: tester
          file: riung/build/ios/iphoneos/riung_unsigned.ipa
