name: CI/CD Build and Distribute

on:
  push:
    branches:
      - master
      - main

jobs:
  build-android:
    name: Build and Distribute Android
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./riung
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Setup Firebase Config Files
        run: |
          cat << 'EOF' > android/app/google-services.json
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: tester
          file: riung/build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./riung
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Setup Firebase Config Files
        run: |
          cat << 'EOF' > ios/Runner/GoogleService-Info.plist
          ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
          EOF

      - name: Install dependencies
        run: flutter pub get

      - name: Build unsigned iOS App
        run: flutter build ios --release --no-codesign

      - name: Create Unsigned IPA
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -qq -r riung_unsigned.ipa Payload
          rm -rf Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: riung/build/ios/iphoneos/riung_unsigned.ipa


